[package]
name = "tracing-sample"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tracing-serde = "0.2"

serde = "1"
serde_json = "1"

chrono = { version = "0.4", features = ["serde"] }
